version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: encurtador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  encurtador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encurtador
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
